Issue #422: Remove rm statements back to build-release and adjust retry logic

diff --git a/.github/workflows/build-nightly-release-alma9.yml b/.github/workflows/build-nightly-release-alma9.yml
--- a/.github/workflows/build-nightly-release-alma9.yml
+++ b/.github/workflows/build-nightly-release-alma9.yml
@@ -73,13 +73,9 @@ jobs:
           attempt=1
           echo "First build attempt failed due to a FetchError. Will retry up to $max_attempts times."
           while (( attempt <= max_attempts )); do
-            echo "DEBUG LS: $(ls)"
-            echo "SPACK_AREA: $SPACK_AREA"
-            rm -rf ${SPACK_AREA}/spack-installation
-            rm -rf spack-${SPACK_VERSION}/spack-repo
-            rm -rf spack-${SPACK_VERSION}/default
-            daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR core $OS ${{ github.event.inputs.feature-branch }} && break
-            echo "Retry attempt $attempt/$max_attempts failed."
+            daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR core $OS ${{ github.event.inputs.feature-branch }}
+            if [[ $? -ne 111 ]]; then break; fi
+            echo "Retry attempt $attempt/$max_attempts failed due to a FetchError."
             attempt=$((attempt+1))
           done
         fi
