Troubleshoot arg parsing

diff --git a/.github/workflows/nightly-ci-dashboard.yml b/.github/workflows/nightly-ci-dashboard.yml
--- a/.github/workflows/nightly-ci-dashboard.yml
+++ b/.github/workflows/nightly-ci-dashboard.yml
@@ -40,9 +40,11 @@ jobs:
     - name: Get workflow run IDs
       id: run_ids
       run: |
+        echo "BRANCH is $BRANCH"
         get_run_id() {
           local workflow="$1"
           local branch="${2:-develop}"
+          echo "Local branch is $branch" &>2
 
           run_id=$(
             gh run list \
@@ -56,7 +58,7 @@ jobs:
             )
 
             if [[ -z "$run_id" || "$run_id" == "null" ]]; then
-              echo "ERROR: Got null or empty workflow ID for '${workflow}' using branch '$branch'" >&2
+              echo "ERROR: Got null or empty workflow ID for '${workflow}' using branch '${branch}'" >&2
               return 1
             fi
 
